name: 'Random Emojii'
description: 'Update a line of text in the README with an emojii'
inputs:
  list_of_emojiis: # list of emojiis to randomly select from
    description: 'string of emojiis to choose from seperated by a space'
    required: false
    default: '🍎 🌶 🍜 🏀 🏆 😀 😱 😤'
  gh_base_url: # base url for github repo to create emojii
    description: "Base url to create PR for triggering emojii change in README"  
    required: false
    default: ${{ github.repository }}
outputs:
  random_url: 
    description: 'URL associated with the next emojii generation'
runs:
  using: 'node12'
  main: 'dist/index.js'
