name: 'Random Emojii'
description: 'Update a line of text in the README with an emojii'
inputs:
  token:  # github token for updating readme
    description: 'Token for intereacting with a repository'
    required: true
    default: ${{ github.token }}
  listOfEmojiis: # list of emojiis to randomly select from
    description: 'string of emojiis to choose from'
    default: '🍎🌶🍜🏀🏆😀😱😤`
runs:
  using: 'node12'
  main: 'dist/index.js'
